### ISSUE TITLE
[bug] `yarn write-translations —locale zh` error

### ISSUE THREAD

**Issue by geometryolife** [starcoinorg/starcoin-cookbook#164]
# Document Bug Report

**Describe the document's bug:**

[ERROR] Error while attempting to extract Docusaurus translations from source code file at "node_modules/@cmfcmf/docusaurus-search-local/lib/client/theme/SearchBar/generated.d.ts".
[ERROR] SyntaxError: /home/ubuntu/i/starcoin-cookbook/node_modules/@cmfcmf/docusaurus-search-local/lib/client/theme/SearchBar/generated.d.ts: Missing initializer in const declaration. (2:32)

  1 | export function tokenize(input: any): any[];
> 2 | export const mylunr: typeof lunr;
    |                                 ^
  3 | import * as lunr from "lunr";
  4 |
    at instantiate (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:359:12)
    at Object.raise (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3339:19)
    at Object.parseVar (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:15383:16)
    at Object.parseVarStatement (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:15176:10)
    at Object.parseVarStatement (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10323:31)
    at Object.parseStatementContent (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:14718:21)
    at Object.parseStatementContent (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:10364:18)
    at Object.parseStatement (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:14643:17)
    at Object.parseExportDeclaration (/home/ubuntu/i/starcoin-cookbook/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:16023:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by geometryolife** [comment]
https://github.com/cmfcmf/docusaurus-search-local/issues/129
